name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Android NDK
        run: yes | sdkmanager "ndk;21.0.6113669" >/dev/null
      # - name: Setup Cmake
      # run: yes | sdkmanager "cmake;3.10.2.4988404" >/dev/null
      # export PATH=$PATH:$ANDROID_HOME/cmake/3.10.2.4988404/bin
      - name: Set default rust toolchain
        run: rustup default 1.61.0
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Install clippy
        run: rustup component add clippy
      - name: Add armv7 target
        run: rustup target add armv7-linux-androideabi
      - name: Add aarch64 target
        run: rustup target add aarch64-linux-android
      - name: Add i686 target
        run: rustup target add i686-linux-android
      - name: Add x86_64 target
        run: rustup target add x86_64-linux-android
      - name: Lint code format
        run: cargo fmt --all -- --check
      # - name: Lint code
      #   run: cargo clippy --all -- -D warnings
      - name: Build aar
        run: ./gradlew assembleRelease
